name: dashtech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.12+32

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basics
  get: ^3.26.0
  flutter_form_builder: ^5.0.0-alpha.1
  flutter_inappwebview: ^4.0.0+4
  intl: ^0.17.0

  # Storage
  get_storage: ^1.4.0

  # Ui @ FX
  flutter_hooks: ^0.15.0
  flutter_svg: ^0.19.3
  lottie: ^0.7.0+1
  animate_do: ^1.7.3
  animated_bottom_navigation_bar: ^0.1.3
  flutter_slidable: ^0.5.7
  shimmer: ^1.1.2
  table_calendar: ^2.3.3
  fl_chart: ^0.20.1
  fab_circular_menu: ^1.0.1

  # Networking
  dio: ^3.0.10
  gql_dio_link: ^0.0.4
  gql_http_link: ^0.3.2
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  graphql_flutter: ^4.0.1

  # Utils
  flutter_screenutil: ^3.2.0
  flutter_dotenv: ^2.1.0
  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  enum_to_string: ^1.0.14
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0
  jwt_decoder: ^1.0.3
  device_info: ^1.0.0
  firebase_messaging: ^7.0.3
  package_info: 0.4.3+2
  pull_to_refresh: 1.6.4
  basic_utils: ^2.6.3
  cached_network_image: ^2.5.0
  expandable: ^4.1.4

  # Icons
  line_icons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  freezed: ^0.12.3
  #lint: ^1.5.1

dependency_overrides:
  path_drawing: ^0.5.0-nullsafety.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - assets/img/
    - .env.dev
    - .env.prod
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttf
