name: flutter_file_store
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.3+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basics
  get: ^3.23.1
  flutter_form_builder: ^3.14.1
  flutter_inappwebview: ^4.0.0+4

  # Storage
  get_storage: ^1.3.2

  # Ui @ FX
  flutter_hooks: ^0.15.0
  flutter_svg: ^0.19.2+1
  lottie: ^0.7.0+1
  animate_do: ^1.7.3
  animated_bottom_navigation_bar: ^0.1.3

  # Networking
  dio: ^3.0.10
  gql_dio_link: ^0.0.4
  gql_http_link: ^0.3.2
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  graphql_flutter: ^3.1.0

  # Utils
  flutter_screenutil: ^3.2.0
  flutter_dotenv: ^2.1.0
  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  enum_to_string: ^1.0.14
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0
  jwt_decoder: ^1.0.3
  device_info: ^1.0.0
  firebase_messaging: ^7.0.3
  package_info: ^0.4.3

  # Icons
  line_icons: ^0.2.0
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  freezed: ^0.12.3
  #lint: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - .env.dev
    - .env.prod
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttf
