name: dashtech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.17+37

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Getx related packages
  get: ^4.1.4
  get_storage: ^2.0.2

  # Ui @ Fxs
  flutter_svg: ^0.22.0
  animate_do: ^2.0.0
  lottie: ^1.0.1
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_calendar: ^19.2.46
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  line_icons: ^2.0.1
  animated_bottom_navigation_bar: ^0.3.2
  expandable: ^5.0.1
  flutter_slidable: ^0.6.0
  fab_circular_menu: ^1.0.2

  # Networking
  gql_http_link: ^0.4.0
  gql_transform_link: ^0.2.0
  gql_error_link: ^0.2.0
  ferry: ^0.10.3
  ferry_hive_store: ^0.4.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1

  # Utils
  flutter_form_builder: ^6.0.1
  flutter_hooks: ^0.18.0
  package_info: ^2.0.2
  enum_to_string: ^2.0.1
  flutter_dotenv: ^5.0.0
  dartz: ^0.10.0-nullsafety.2
  flutter_nfc_kit: ^2.2.1
  flutter_inappwebview: ^5.3.2
  device_info: ^2.0.2
  basic_utils: ^3.3.3

  # Firebase
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  freezed: ^0.14.2
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  ferry_generator: ^0.4.3
  gql_build: ^0.2.0
  gql_code_builder: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - assets/img/
    - .env.dev
    - .env.prod
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttf
