name: dashtech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.13+33

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basics
  get: ^4.1.4
  flutter_form_builder: ^6.0.0
  flutter_inappwebview: ^5.3.2
  intl: ^0.17.0

  # Storage
  get_storage: ^2.0.2

  # Ui @ FX
  flutter_hooks: ^0.16.0
  flutter_svg: ^0.22.0
  lottie: ^1.0.1
  animate_do: ^2.0.0
  animated_bottom_navigation_bar: ^0.3.2
  flutter_slidable: ^0.6.0
  shimmer: ^2.0.0
  table_calendar: ^3.0.0
  fl_chart: ^0.35.0
  fab_circular_menu: ^1.0.1

  # Networking
  dio: ^4.0.0
  gql_dio_link: ^0.1.0-nullsafety.1
  gql_http_link: ^0.4.0-nullsafety.1
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  graphql_flutter: ^5.0.0-nullsafety.2

  # Utils
  flutter_screenutil: ^5.0.0
  flutter_dotenv: ^3.1.0
  freezed_annotation: ^0.14.1
  dartz: ^0.9.2
  enum_to_string: ^2.0.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.1
  jwt_decoder: ^2.0.1
  device_info: ^2.0.0
  firebase_messaging: ^9.1.2
  package_info: ^2.0.0
  pull_to_refresh: ^1.6.5
  basic_utils: ^3.0.2
  cached_network_image: ^3.0.0
  expandable: ^5.0.1

  # Icons
  line_icons: ^2.0.1
  syncfusion_flutter_calendar: ^19.1.57
  firebase_core: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  #lint: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - assets/img/
    - .env.dev
    - .env.prod
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttf
